# Prometheus Configuration for PromptPilot
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape PromptPilot backend metrics
  - job_name: 'promptpilot-backend'
    static_configs:
      - targets: ['backend:8001']  # Using Docker service name
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Scrape PostgreSQL metrics (if postgres_exporter is running)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Scrape Redis metrics (if redis_exporter is running)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
# rule_files:
#   - "alert_rules.yml"